package com.spacex.trelloassistant.models;
import java.util.Arrays;
import java.util.List;


public class CamposDatosPlantillaConstantes {

    private CamposDatosPlantillaConstantes() {
    }
        public static final String TITULO_SEO_ES = "Titulo SEO (ES)";
        public static final String TITULO_SEO_EN = "Titulo SEO (EN)";
        public static final String ID = "ID";
        public static final String METADESCRIPTION_SEO_ES = "Metadescription SEO (ES)";
        public static final String METADESCRIPTION_SEO_EN = "Metadescription SEO (EN)";
        public static final String REL_CANONICAL = "Rel canonical";
        public static final String SLUG_ES = "SLUG(ES)";
        public static final String SLUG_EN = "SLUG(EN)";
        public static final String KEYWORDS_ES = "Keywords (ES)";
        public static final String KEYWORDS_EN = "Keywords (EN)";
        public static final String BREDCRUMB1_ES = "Bredcrumb1 (ES)";
        public static final String TITULO_PAGINA_ES = "Titulo pagina (ES)";
        public static final String TITULO_PAGINA_EN = "Titulo pagina (EN)";
        public static final String TITULO_CURSO_ES = "Titulo de curso (ES)";
        public static final String TITULO_CURSO_EN = "Titulo de curso (EN)";
        public static final String TIPO_CURSO_ES = "Tipo de Curso (ES)";
        public static final String TIPO_CURSO_EN = "Tipo de Curso (EN)";
        public static final String ID_ASSET = "ID del asset de la Imagen de la big card";
        public static final String ID_IMG_CURSO_DESKTOP = "ID IMG curso desktop";
        public static final String ID_IMG_CURSO_MOBILE = "ID IMG curso mobile";
        public static final String DESCRIPCION_ES = "Descripción (ES)";
        public static final String DESCRIPCION_EN = "Descripción (EN)";
        public static final String CODIGO_EVENTO_CON_COSTO = "Codigo Evento - (Con costo) ";
        public static final String ENLACE_INSCRIPCIÓN_SIN_COSTO = "Enlace inscripción sin costo";
        public static final String RUTA_CURSO_TARJETA_SABE_MAS_ES = "Ruta del curso (link de la tarjeta - Saber más) (ES)";
        public static final String RUTA_CURSO_TARJETA_SABE_MAS_EN = "Ruta del curso (link de la tarjeta - Saber más) (EN)";
        public static final String AREA_ES = "Area (ES)";
        public static final String AREA_EN = "Area (EN)";
        public static final String MODALIDAD_ES = "Modalidad (ES)";
        public static final String MODALIDAD_EN = "Modalidad (EN)";
        public static final String SECTOR_ES = "Sector (ES)";
        public static final String SECTOR_EN = "Sector (EN)";
        public static final String LUGAR_ES = "Lugar (ES)";
        public static final String LUGAR_EN = "Lugar (EN)";
        public static final String FECHA_INICIO_ES = "Fecha de inicio (ES)";
        public static final String FECHA_INICIO_EN = "Fecha de inicio (EN)";
        public static final String FECHA_FINALIZACION_ES = "Fecha de finalización (ES)";
        public static final String FECHA_FINALIZACION_EN = "Fecha de finalización (EN)";
        public static final String HORARIO_ES = "Horario (ES)";
        public static final String HORARIO_EN = "Horario (EN)";
        public static final String COSTO_ES = "Costo (ES)";
        public static final String PRECIO = "Precio";
        public static final String MOSTRAR_LIKES = "Mostrar Likes";
        public static final String MOSTRAR_COMPARTIR = "Mostar compartir";
        public static final String MOSTRAR_INSCRIPTOS = "Mostar inscriptos";
        public static final String SELECCIONAR_COMO_BIG_CARD = "Seleccionar como Big Card";
        public static final String MOSTRAR_EN_INICIO = "Mostrar en inicio";
        public static final String MOSTRAR_NUEVO_LANZAMIENTO = "Mostrar nuevo lanzamiento";
        public static final String METODOLOGIA_ES = "Metodologia (ES)";
        public static final String METODOLOGIA_EN = "Metodologia (EN)";
        public static final String CONTENIDO_ES = "Contenido (ES)";
        public static final String CONTENIDO_EN = "Contenido (ES";
        public static final String CIERRE_INSCRIPCION_ES = "Cierre de inscripción (ES)";
        public static final String REQUISITOS_EN = "Requisitos (ES)";
        public static final String REQUISITOS_ES = "Requisitos (EN)";
        public static final String DIRIGIDO_EN = "Requisitos (EN)";
        public static final String DIRIGIDO_ES = "Dirigido a (EN)";
        public static final String CERTIFICACION_ES = "Certificación (ES)";
        public static final String CERTIFICACION_EN = "Certificación (EN)";
        public static final String SESIONES_ES = "Sesiones (ES)";
        public static final String SESIONES_EN = "Sesiones (EN)";


    List<String> id  = Arrays.asList("ID", "id");
    List<String> cursoEs  = Arrays.asList("Titulo SEO (ES)", "TituloSEO(ES)");
    List<String> cursoEn = Arrays.asList("Titulo SEO (EN)", "TituloSEO(EN)");
    List<String> metadescriptionEs = Arrays.asList("Metadescription SEO (ES)");
    List<String> metadescriptionEn = Arrays.asList("Metadescription SEO (EN)");
    List<String> relCanonical = Arrays.asList("Rel canonical");
    List<String> slugEs = Arrays.asList("SLUG(ES)");
    List<String> slugEn = Arrays.asList("SLUG(EN)");
    List<String> keywordsEs = Arrays.asList("Keywords (ES)");
    List<String> keywordsEn = Arrays.asList("Keywords (EN)");
    List<String> bredcrumb1ES = Arrays.asList("Bredcrumb1 (ES)");
    List<String> tituloPaginaEs = Arrays.asList("Titulo pagina (ES)");
    List<String> tituloPaginaEn = Arrays.asList("Titulo pagina (EN)");
    List<String> tituloCursoEs = Arrays.asList("Titulo de curso (ES)");
    List<String> tituloCursoEn = Arrays.asList("Titulo de curso (EN)");
    List<String> tipoCursoEs = Arrays.asList("Tipo de Curso (ES) (seminario, taller…)", "Tipo de Curso (ES)");
    List<String> tipoCursoEn = Arrays.asList("Tipo de Curso (EN) (seminario, taller…)", "Tipo de Curso (EN)");
    List<String> idAssetImagen = Arrays.asList("ID del asset de la Imagen de la big card", "Id Asset Imagen");
    List<String> idImgDesktop = Arrays.asList("ID IMG curso desktop");
    List<String> idImgMobile = Arrays.asList("ID IMG curso mobile");
    List<String> descripcionEs = Arrays.asList("Descripción (ES)");
    List<String> descripcionEn = Arrays.asList("Descripción (EN)");
    List<String> codigoEventoConCosto = Arrays.asList( "Codigo Evento - (Con costo) ");
    List<String> enlaceInscripciónSinCosto = Arrays.asList( "Enlace inscripción sin costo");
    List<String> rutaCursoTarjetaSabeMasEs = Arrays.asList("Ruta del curso (link de la tarjeta - Saber más) (ES)");
    List<String> rutaCursoTarjetaSabeMasEn = Arrays.asList("Ruta del curso (link de la tarjeta - Saber más) (EN)");
    List<String> areaEs = Arrays.asList( "Area (ES)");
    List<String> areaEn = Arrays.asList( "Area (EN)");
    List<String> modalidadEs = Arrays.asList( "Modalidad (ES)");
    List<String> modalidadEn = Arrays.asList( "Modalidad (EN)");
    List<String> sectorEs = Arrays.asList( "Sector (ES)");
    List<String> sectorEn = Arrays.asList( "Sector (EN)");
    List<String> lugarEs = Arrays.asList( "Lugar (ES)");
    List<String> lugarEn = Arrays.asList( "Lugar (EN)");
    List<String> fechaInicioEs = Arrays.asList( "Fecha de inicio (ES)");
    List<String> fechaInicioEn = Arrays.asList( "Fecha de inicio (EN)");
    List<String> fechaFinalizacionEs = Arrays.asList( "Fecha de finalización (ES)");
    List<String> fechaFinalizacionEn = Arrays.asList( "Fecha de finalización (EN)");
    List<String> horarioEs = Arrays.asList( "Horario (ES)");
    List<String> horarioEn = Arrays.asList( "Horario (EN)");
    List<String> costoEs = Arrays.asList( "Costo (ES)");
    List<String> precio = Arrays.asList( "Precio");
    List<String> mostrarLikes = Arrays.asList( "Mostrar Likes");
    List<String> mostrarCompartir = Arrays.asList( "Mostar compartir");
    List<String> mostrarInscriptos = Arrays.asList( "Mostar inscriptos");
    List<String> seleccionarComoBigCard = Arrays.asList( "Seleccionar como Big Card");
    List<String> mostrarEnInicio = Arrays.asList( "Mostrar en inicio");
    List<String> mostrarNuevoLanzamiento = Arrays.asList( "Mostrar nuevo lanzamiento");
    List<String> metodologiaEs = Arrays.asList( "Metodologia (ES)");
    List<String> metodologiaEn = Arrays.asList( "Metodologia (EN)");
    List<String> contenidoEs = Arrays.asList( "Contenido (ES)");
    List<String> contenidoEn = Arrays.asList( "Contenido (ES");
    List<String> cierreInscripcionEs = Arrays.asList( "Cierre de inscripción (ES)");
    List<String> requisitosEn = Arrays.asList( "Requisitos (ES)");
    List<String> requisitosEs = Arrays.asList( "Requisitos (EN)");
    List<String> dirigidoEn = Arrays.asList( "Requisitos (EN)");
    List<String> dirigidoEs = Arrays.asList( "Dirigido a (EN)");
    List<String> certificacionEs = Arrays.asList( "Certificación (ES)");
    List<String> certificacionEn = Arrays.asList( "Certificación (EN)");
    List<String> sesionesEs = Arrays.asList( "Sesiones (ES)");
    List<String> sesionesEn = Arrays.asList( "Sesiones (EN)");

}

